trigger: none

pr:
  branches:
    include:
      - trunk

pool:
  vmImage: 'ubuntu-latest'

variables:
  TARGET_RELEASE_REQUIRED: 'v16.LTS'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: |
      pip install requests
    displayName: 'Install dependencies'

  - script: |
      python3 scripts/validate_target_release.py
    displayName: 'Validate DeltaV Target Release'
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      TARGET_RELEASE_REQUIRED: $(TARGET_RELEASE_REQUIRED)
